version: "3.8"
services: 
  mysql_init:
    image: hashicorp/terraform
    volumes:
    - ./mysql:/template
    working_dir: /template 
    command: init
  
  mysql_deploy:
    image: hashicorp/terraform 
    volumes:
    - ./mysql:/template
    working_dir: /template 
    environment:
      - TF_VAR_MYSQL_DATABASE=$MYSQL_DB
      - TF_VAR_MYSQL_ROOT_PASSWORD=$MYSQL_PASS
      - TF_VAR_ECS_NAME=$ECS_NAME 
      - TF_VAR_VPC_ID=$VPC_ID
    command: apply -auto-approve
    depends_on:
      mysql_init:
        condition: service_completed_successfully
      
  webserver_init:
    image: hashicorp/terraform
    volumes:
    - ./webserver:/template
    working_dir: /template 
    command: init
  
  webserver_deploy:
    image: hashicorp/terraform 
    volumes:
    - ./webserver:/template
    working_dir: /template 
    command: apply -auto-approve
    environment:
      - TF_VAR_ECS_NAME=$ECS_NAME 
      - TF_VAR_VPC_ID=$VPC_ID
    depends_on:
      webserver_init:
        condition: service_completed_successfully