version: "3.8"
services: 
  panayadb:
    image: panayadb
    hostname: panayadb
    environment:
      - MYSQL_ROOT_PASSWORD="secretpass"
      - MYSQL_DATABASE="panaya"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  webserver:
    build: 
      context: ./webserver
      args:
      - MYSQL_HOST=panayadb
      - MYSQL_USER=root
      - MYSQL_PASS=secretpass
      - MYSQL_DB=panaya
    hostname: panayaserver
    ports:
    - "8080:80"
    depends_on:
      panayadb:
        condition: service_healthy
    networks:
      - app-network
networks:
  app-network:
    driver: bridge